name: Deploy Test PWA

on:
  push:
    branches:
      - test  # Запускаем при пуше в ветку test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Клонируем репозиторий
        uses: actions/checkout@v3

      - name: 📦 Устанавливаем зависимости
        run: npm install

      - name: 🏗️ Собираем проект
        run: npm run build

      - name: 🚀 Деплоим тестовую версию
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Деплой из корня
          publish_branch: test  # Тестовая ветка для деплоя
